### ISSUE TITLE
Image type should not resize width in grid mode

### ISSUE THREAD

**Issue by christabor** [christabor/flask_jsondash#115]
If the layout is grid, it should not set the width to 100% as this guarantees the aspect ratio will almost never be exactly right.

If in grid mode, width should just be auto, and will automatically be filled in based on the given height.

**Comment by choimosi** [comment]
I have similar problem.
I'm using Win10 with VMWARE 
When I open the chart in win10 with chrome, it looks like below. 
![image](https://user-images.githubusercontent.com/34368808/37724601-7ff763f8-2d74-11e8-92b1-0dc7aeaf0020.png)
When I open the chart in ubuntu, vmware with chromium, it looks like below.
![image](https://user-images.githubusercontent.com/34368808/37724805-efc4dec2-2d74-11e8-83a7-549e4a377b5e.png)
When I open the chart in ubuntu, vmware with firefox, it looks like below.
![image](https://user-images.githubusercontent.com/34368808/37724834-fccf28a2-2d74-11e8-920f-f9f63b6c04a0.png)

any suggestion? in order to change chart width and position.

**Comment by choimosi** [comment]
when I draw more charts 3*2, it is working fine.
thanks
