### ISSUE TITLE
example_app$ python3 app.py does not work

### ISSUE THREAD

**Issue by olzhas23** [christabor/flask_jsondash#158]
Traceback (most recent call last):
  File "app.py", line 7, in <module>
    from flask_jsondash.charts_builder import charts
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_jsondash-6.3.3-py3.5.egg/flask_jsondash/charts_builder.py", line 26, in <module>
    from .utils import (
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/flask_jsondash-6.3.3-py3.5.egg/flask_jsondash/utils.py", line 15, in <module>
    import charts_builder
ImportError: No module named 'charts_builder'

**Comment by Zhang-WJ** [comment]
This also confuse me.

**Comment by christabor** [comment]
I can reproduce this in python 3.5. Can you try in 2.7 just to confirm? If so, then something is up with the imports. At one point all tests have passed under 2.7-3.6, but Travis has been failing and I haven't had time to dig in. I suspect this is related.

**Comment by turing4ever** [comment]
It seems that it's a circular import issue. I don't think it has anything to do with python versions. 
Modified the code a bit and created a PR: https://github.com/christabor/flask_jsondash/pull/160

**Comment by Harold2017** [comment]
try this:
from . import charts_builder.py

**Comment by acstott** [comment]
So the issue is that the utils.py file contains an import charts_builder statement but charts_builder.py somehow depends on utils (I haven't read through all the src yet). 

The workaround for me was:

1.) Install any dependencies that setup.py missed (for me was cerberus and pymongo)

2.) Remove import charts_builder from utils.py file

3.) Added import flask_jsondash in app.py 

4.) Copy the app.py file from the example_app directory to one level up (For me this was required to make flask_jsondash module imports work)

5.) run python3 app.py  

So this worked to get the app up and running without any import errors, however now I am getting a mongodb connection refused error - fun times

**Comment by christabor** [comment]
There was a circular import where utils imports charts_builder, but only needed a sub-folder import within that namespace, so it caused an issue. I fixed that and it works locally when testing in python2.7 and 3.5.

See https://github.com/christabor/flask_jsondash/pull/162 for more details.
